### PR TITLE
Bug invalid tree root

### LINKED ISSUE #7: tree.root may become invalid
Removing the root node with any remove method does not reset tree.root to None.

root_node_id will return an invalid Id in that case.

### PR DESCRIPTION
**Pull request by iwburns**
Fixes #7 

@Drakulix I would love your input on this if you have time.  Can you see anything that I missed?

### CODE REVIEW

File: src/tree.rs [hunk 1]
```diff
@@ -331,24 +331,15 @@ impl<T> Tree<T> {
...
-                .clone();
-
-            for child_id in children {
+        if let Some(parent_id) = self.get_unsafe(&node_id).parent().cloned() {
+            //attach children to parent
+            for child_id in self.get_unsafe(&node_id).children().clone() {
                 self.set_as_parent_and_child(&parent_id, &child_id);
             }
+        } else {
+            self.clear_parent_of_children(&node_id);
```
Comment (Drakulix) [inline src/tree.rs]: Is this the best way to handle this?

I think using `remove_node_lift_children` on the root should be an `Error`, because there is no way to lift them in that case. Making them orphans is unexpected, don't you think so?

Comment (iwburns) [inline src/tree.rs]: So, I went back and forth over this for a while back when I first wrote it.

I don't like this behavior to be honest, but for whatever reason (I can't seem to remember why) I decided that this was the best way to go a that time.

Sadly, changing this would be another breaking change as this behavior is documented this way, so some people might be depending on it.  In addition, to return an `Error` I would need a new type of `Error` to return.

I'm not against changing this behavior, but it would have to wait until the bump to 1.0.0 I think.

Comment (Drakulix) [inline src/tree.rs]: If it is documented, it is not as unexpected, as I did imagine it at first.
Definitely still something, that should be on the long-term todo list, but I think then this is good for merge.

Comment (iwburns) [inline src/tree.rs]: I agree, and thanks for taking a look!
